Repository trusteddomainproject/OpenDKIM, pull requests merged in 2020-10, with the labels that each got.

#81 logical-error-fix
  opendkim/opendkim-genzone.c
Labels: bug, enhancement

#65 Suppress empty brackets in syslog startup message
  opendkim/opendkim.c
Labels: enhancement

#58 miltertest: Fix undefined behaviour in mt.eom_check() with MT_SMTPREPLY
  miltertest/miltertest.c
Labels: bug

#34 Fix unknown operator in configure.ac
  configure.ac
Labels: bug

#55 miltertest: Fix broken mt.data() function
  miltertest/miltertest.c
Labels: bug

#101 ed25519 support
  opendkim/opendkim-genkey.8.in
  opendkim/opendkim-genkey.in
Labels: enhancement
